### ISSUE TITLE
Implement keyboard navigation

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#17]
As a minimal implementation: when in a codelab step, users should be able to havigate to next/prev steps using left/right arrows. This is also used in some in-person led tranining with a pointer device which can emit keyboard events.

Also see https://github.com/googlecodelabs/codelab-components/issues/46 and  https://github.com/googlecodelabs/codelab-components/pull/48 for additional features requested, related to keyboard navigation.

**Comment by skarEE** [comment]
Fixed.
