### ISSUE TITLE
Replace google-codelab's title attribute with something else

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#28]
The `title` attribute makes a browser display a tooltip while hovering on any part of text or empty space of a codelab step:

![image](https://user-images.githubusercontent.com/25405/39134260-81b8426e-4716-11e8-8ea0-e3d8ae2a1192.png)

We should deprecate the `title` attribute and use something else which wouldn't cause a tooltip to pop up. Maybe use `name` instead? Note that we shouldn't remove the `title` completely for backward compatibility, just encourage usage of the new attribute and mark the old one as `@deprecated`.

See https://github.com/googlecodelabs/about/issues/11 for more details.

**Comment by skarEE** [comment]
Fixed

**Comment by x1ddos** [comment]
Reopening to indicate this hasn't been rolled out to the public site yet. Will close when it is.

**Comment by kwalrath** [comment]
Isn't this fixed now?

**Comment by griadooss** [comment]
Still annoying everyone .... PLEASE turn this damn thing OFF!

![screenshot_20181125_121823](https://user-images.githubusercontent.com/5284608/48974411-8ae36680-f0ac-11e8-8f05-61e468019e77.png)

**Comment by mohityadav7** [comment]
Please fix this! It's aggravating.

**Comment by chalin** [comment]
We're nearing the end of Q4, is there any change this fix will be published soon? cc @kwalrath

**Comment by shawnbuso** [comment]
Tracking remaining work in https://github.com/googlecodelabs/tools/issues/128
