### ISSUE TITLE
Show completed tutorials as "completed" on home page

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#31]
Moving the issue from https://github.com/googlecodelabs/tools/issues/22 by @Akshar-Patel here:

I have completed constraint layout tutorial, but it is not saving up the progress when I reopen it and there is no indication of completion on the home page.

**Comment by shawnbuso** [comment]
Now that codelab-elements code is in tools, closing this to track in googlecodelabs/tools#22.
