### ISSUE TITLE
Keyboard Navigation on Codelabs does not keep sidepane focus in view

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#37]
From internal report:

Using keyboard to navigate(left/right arrows) updates the highlight on the left sidebar, but it can go out of view on longer codelabs.

Repro: 
Start a codelab which has 10+ steps in a small window.  Scroll to the bottom of the sidebar list.  Navigate using Left/Right.  Note the highlight is not visible / focused.  I would expect on keypress the highlight would be re-focused.

**Comment by shawnbuso** [comment]
This appears to be fixed - I can repro on codelabs.developers.google.com but not on the preview server or on a local dev instance.
