### ISSUE TITLE
Missing pretty check marks in "What you'll learn"

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#44]
I think something's missing in the CSS. Here's how it looks now:

![image](https://user-images.githubusercontent.com/25405/42449748-26573ad0-8382-11e8-8218-9dc9fe2c8821.png)

and here's how it's supposed to look like:

![image](https://user-images.githubusercontent.com/25405/42449776-3aa7be9c-8382-11e8-8782-ff1527e82230.png)

**Comment by shawnbuso** [comment]
I looked into this as an easy starter bug, and it looks like Sass just doesn't like [the "::content" selector in our stylesheet](https://github.com/googlecodelabs/codelab-elements/blob/master/google-codelab-step/google_codelab_step.scss#L161) - if I remove that it works as expected. Does anyone know a) if this is expected to work in Sass, and b) if we actually need that selector? It looks like it was just copied over from codelab-components, and it's the only instance of "::content" in any of our stylesheets.

**Comment by shawnbuso** [comment]
@x1ddos it looks like you added the "::content" selector in [this PR](https://github.com/googlecodelabs/codelab-elements/commit/be7033eeed2d1041f06164ae9b61fe8e9ab86e80#diff-eb9767054b43fb056ba5172987ca8d93R144). Do you remember why that was? Based on my reading about it I think it's safe to remove, but wanted to check since it was explicitly added there and not just some copy-pasta.

**Comment by sethvargo** [comment]
`::content` is a shadowDOM selector ([ref](https://stackoverflow.com/questions/35168009/what-is-content-in-a-css))

For safety, we could change that to:

```scss
google-codelab-step .instructions ::content ul.checklist li,
google-codelab-step .instructions ul.checklist li {

}
```

**Comment by x1ddos** [comment]
> @x1ddos it looks like you added the "::content" selector in this PR. Do you remember why that was?

@shawnbuso no I don't because it wasn't me :) look at the commit author username.

**Comment by shawnbuso** [comment]
Oh whoops, not sure how I made that mistake, I think I misclicked in the blame layer :) In any case, I think @sethvargo's suggested approach is probably best so I have a PR out now with that, #55.
