### ISSUE TITLE
Provide compiled elements package for distribution  

### ISSUE THREAD

**Issue by x1ddos** [googlecodelabs/codelab-elements#6]
When #2 is closed, the same CI instance could also package the build artifacts and upload them to the Releases tab of this repo when a new commit tag is pushed.

Maybe also upload it to npm and whatever people use these days.
Related request in the original repo: https://github.com/googlecodelabs/codelab-components/issues/43

**Comment by x1ddos** [comment]
@abitrolly yes, bazel can do all sorts of queries: https://docs.bazel.build/versions/master/query-how-to.html

**Comment by shawnbuso** [comment]
Tracking in https://github.com/googlecodelabs/tools/issues/130
